*** Variables ***
${pagina_login}             xpath=//*[@resource-id="view-login"]
${campo_email}              xpath=//*[@resource-id="loginEmail"]
${campo_senha}              xpath=//*[@resource-id="loginSenha"]
${olho_senha}               xpath=//*[@resource-id="olhoLoginSenha"]
${botao_entrar}             xpath=//*[@resource-id="botaoEntrar"]
${link_cadastro}            xpath=//*[@resource-id="linkCadastro"]
${link_esqueci_senha}       xpath=//*[@resource-id="linkEsqueciSenha"]
${toast_login}              xpath=//*[@resource-id="toastLogin"]
